### ISSUE TITLE
Code Analysis Warning CA2243

### ISSUE THREAD

**Issue by bdhess** [ParticularLabs/GitVersion#334]
When Microsoft All Rules is enabled alongside the GitVersion task, the following error arises.

MSBUILD : warning CA2243: Microsoft.Usage : In the constructor of 'AssemblyInformationalVersionAttribute', change the value of argument 'informationalVersion', which is currently "1.1.0-dev+27.Branch.dev.Sha.4e1b789cfbb47b1dd6bc8f00d1ca7bfa7263199d", to something that can be correctly parsed as 'Version'.

No status on a fix from MS:
https://connect.microsoft.com/VisualStudio/feedback/details/796535/the-ca2243-rule-attribute-string-literals-should-parse-correctly-should-not-be-applied-to-assemblyinformationalversionattrubute

However, without a code change in GitVersion, the only workaround is to disable the rule entirely for all assemblies that use GitVersion.  This seems undesirable.

**Comment by bdhess** [comment]
This issue previously discussed in #77

**Comment by gep13** [comment]
Hello @bdhess,

I am not sure that there is really anything that can be done about this, except make the GlobalSuppression as you have pointed out.  The version number that is being set in the InformationalVersion attribute is a valid Semantic Version number, the problem is that FxCop is not parsing it as a Semantic Version Number, but rather a standard four part version number.

In your case, assuming you are not using the InformationVersion attribute, if you omit it from the AssemblyInfo file, GitVersion shouldn't add it (or at least it doesn't for the standard GitVersion.exe (which is what I use) and I am assuming that it is the same for GitVersionTask.

Hope that helps!

Gary

**Comment by bdhess** [comment]
Thanks @gep13 -- I'm using the MSBuild task, with no version information in my AssemblyInfo file, so all of the properties get generated by default.  The only solution I can think of to keep the version attribute _and_ pass the rule is reflecting into the fxcop class, where a private array of exceptions to the rules is kept.

I think it's fair to close this issue, since the bug is really MS's, and I don't think there's a reasonable workaround in GitVersion.

**Comment by gep13** [comment]
@bdhess sounds like a plan to me! :+1: Thanks for getting back to me.

**Comment by Gaurav-2527** [comment]
Can someone tell how to fix CA2243 at the time MSBuild?
